### ISSUE TITLE
쇼핑몰에 강의 올리기

### ISSUE THREAD

**Issue by Kyeongrok** [Kyeongrok/godomal#1]
고도몰 쇼핑몰에 강의 1개를 올린다

목표는 토요일 오전 11시~2시 강의 1명을 모집하는 것
한명이 두명되고 두명이 세명된다.

4주 과정 20만원
빠졌을때 백업 방법 등을 생각해본다.
http://codingapple.com/ 참고

1. 삼성 비전공자 면접을 준비하기 위한 파이썬 원데이
2. requests, beautifulSoup 등을 이용한 파이썬 데이터 수집 입문
3. pandas, numpy를 이용한 파이썬 데이터 분석 입문
4. aws로 서비스 구축하기
5. 코딩면접 준비를 위한 python 알고리즘

**Comment by go0win** [comment]
http://gys3485.godomall.com/goods/goods_view.php?goodsNo=1000000000
상품 정보 중 구매제한, 배송비, 상품코드는 사이트에 보여줄 필요가 없음.
사이트 아래에 배송안내 등도 필요 없음.
부분 삭제 방법 찾는 중.

**Comment by Kyeongrok** [comment]
패스트캠퍼스
https://www.fastcampus.co.kr/biz_camp_python4auto/

탈잉
https://taling.me/Talent/Detail/3692

코딩애플
http://codingapple.com/goods/goods_view.php?goodsNo=1000000042

**Comment by go0win** [comment]
삼성 비전공자 면접을 준비하기 위한 파이썬 원데이

- 삼성 채용에서 파이썬이 차지하는 비중. 수업 대상 명확히.
- 정가, 특정 시기에 따른 할인가.
- 정확한 날짜와 시간. 장소.
- 준비물. (노트북)
- 문의방법. 전화번호 및 카카오톡 문의.
- 유튜브 강의 gif로 편집.
- FAQ 생각해서 질문과 그에 따른 답변.
